# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-08 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimedCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64)),
                ('code_l', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[('percent', 'percent'), ('value', 'value')], max_length=16)),
                ('expires', models.DateTimeField()),
                ('bound', models.BooleanField(default=False)),
                ('bind', models.CharField(choices=[('user', 'user'), ('email', 'email')], default='user', max_length=16)),
                ('binding', models.CharField(blank=True, max_length=256, null=True)),
                ('repeat', models.IntegerField(default=-1)),
            ],
        ),
        migrations.AddField(
            model_name='claimedcoupon',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupons.Coupon'),
        ),
    ]
